# Generated by Django 4.1.3 on 2022-11-13 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emp_id', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=20)),
                ('com_name', models.CharField(max_length=20)),
                ('com_address', models.TextField(default='-')),
                ('com_contact', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Emploies',
            },
        ),
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_tag', models.CharField(max_length=50)),
                ('asset_model', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('purchase_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracAssets.assetcategory')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
