# Generated by Django 4.1.3 on 2022-11-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracAssets', '0002_assettracks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='assettracks',
            name='return_condition',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assettracks',
            name='return_time',
            field=models.DateField(null=True),
        ),
    ]
