# Generated by Django 4.1.3 on 2022-11-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracAssets', '0003_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettracks',
            name='return_condition',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assettracks',
            name='return_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
