# Generated by Django 4.1.3 on 2022-11-14 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracAssets', '0004_alter_assettracks_return_condition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assettype',
            options={'ordering': ['-id'], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.PositiveIntegerField()),
                ('left_for_check_out', models.PositiveIntegerField()),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracAssets.assetcategory')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'db_table': 'inventory',
                'managed': True,
            },
        ),
    ]
